version: 2 

sources:
  - name: bronze_streamline
    database: streamline
    schema: >-
      {{ var('GLOBAL_PROD_DB_NAME') ~ ('_dev' if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else '') }}
    tables:
      - name: testnet_blocks
      - name: testnet_transactions
      - name: testnet_receipts
      - name: testnet_traces
      - name: testnet_confirm_blocks
      - name: testnet_decoded_logs
      - name: blocks
      - name: transactions
      - name: receipts
      - name: traces
      - name: confirm_blocks
      - name: decoded_logs
      - name: token_reads
      - name: balances_erc20
      - name: balances_native
      - name: contract_abis
      - name: stablecoin_reads
  - name: crosschain_silver
    database: "{{ 'crosschain' if target.database.upper() == var('GLOBAL_PROD_DB_NAME').upper() else 'crosschain_dev' }}"
    schema: silver
    tables:
      - name: labels_combined
      - name: complete_provider_asset_metadata
      - name: complete_native_asset_metadata
      - name: complete_native_prices
      - name: complete_provider_prices
      - name: complete_token_asset_metadata
      - name: complete_token_prices
      - name: tokens_stablecoins
  - name: crosschain_gold
    database: crosschain
    schema: core
    tables:
      - name: dim_dates
  - name: bronze_api
    database: "{{ target.database }}"
    schema: bronze_api
    tables:
      - name: contract_abis
  - name: crosschain_public
    database: crosschain
    schema: bronze_public
    tables:
      - name: user_abis
  - name: complete_streamline
    database: "{{ target.database }}"
    schema: streamline
    tables:
      - name: complete_contract_abis
  - name: github_actions
    database: "{{ target.database }}"
    schema: github_actions
    tables:
      - name: workflows
  - name: external_gold_defillama
    database: external
    schema: defillama
    tables:
      - name: dim_chains
  - name: abis_silver
    database: "{{ target.database }}"
    schema: silver
    tables:
      - name: verified_abis
      - name: complete_event_abis
  - name: fsc_evm_admin
    database: >-
      {{ 'FSC_EVM_DEV' if '_DEV' in target.database.upper() else 'FSC_EVM' }}
    schema: admin
    tables:
      - name: _master_keys
      - name: rpc_node_logs